---
title: "Reporte"
author: "Miguel A. Ortiz Acuna"
date: "6/18/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(lubridate)
library(corrplot)
library(gclus)
library(patchwork)
```

```{r, echo=FALSE}
birth <- read.csv("Datasets/PE_TODOS2.csv")
```


```{r summary}
birth %>%
  clean_names() -> birth # Eu coloquei os nomes em minuscula, nao gosto as maisculas

cols.fact <- c("ano_nasc", "estcivmae" , "escmae" , "racacor")  

birth[cols.fact] <- sapply(birth[cols.fact], as.character)

birth %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(data_nasc = mdy(data_nasc))-> birth


birth %>% 
  mutate(classe = as.character(classe)) %>% 
  mutate(classe = as.factor(classe)) -> birth


numeric_variables <- birth[ , purrr::map_lgl(birth, is.numeric)]
numeric_variables <- numeric_variables[1:9]
```


# Statistics 

```{r}
statistics <- do.call(data.frame, 
                      list(Mean = apply(numeric_variables, 2, mean),
                           Std.dev = apply(numeric_variables, 2, sd),
                           Min = apply(numeric_variables, 2, min),
                           Quantile_1st = apply(numeric_variables, 2, function(x){quantile(x, probs = 0.25)}),
                           Median = apply(numeric_variables, 2, median),
                           Quantile_3rd = apply(numeric_variables, 2, function(x){quantile(x, probs = 0.75)}),
                           Max = apply(numeric_variables, 2, max)))

statistics <- t(statistics)
knitr::kable(statistics)
```

## Numero de nascidos vivos por ano

```{r, fig.align='center'}
cantidad <- birth %>% 
  group_by(data_nasc,ano_nasc) %>% 
  count(data_nasc,sort = F) 
  

ggplot(cantidad, aes(x = ano_nasc, y = n, color = ano_nasc)) +
  geom_boxplot() +
  geom_jitter() +
  scale_color_brewer(type = "qual", palette = 2) +
  theme_minimal() +
  theme(legend.position = "none")+
    labs( x = "",
       y = "Numero de nascidos vivos")

```

## Idade da mae comportamento

```{r, warning=FALSE, message=FALSE, fig.align='center'}
ggplot(birth, aes(x=idademae)) + 
  geom_histogram(aes(y=..density..), colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666")+
  scale_x_continuous(limits = c(9,45), breaks = seq(10, 46,2))+
  theme_classic()+
  labs(x ="")
  
```

## Variaveis discretas 


```{r, fig.align='center', fig.height=5, fig.width=15}

escolaridade <- birth %>% 
  group_by(escmae) %>% 
  summarise(n= n()) %>% 
  arrange(desc(n))

estado <- birth %>% 
  group_by(estcivmae) %>% 
  summarise(n= n())

raca <- birth %>% 
  group_by(racacor) %>% 
  summarise(n= n())


p1<-ggplot(data = escolaridade) + 
  geom_col(mapping = aes(x = escmae, y = n, fill = escmae), show.legend = F)+
  scale_y_continuous(labels = scales::comma)+
  scale_x_discrete(limits = c("1","2", "3", "4", "5"),
                   labels = c("Nenhuma", "1 a 3 anos", "4 a 7 anos", "8 a 11 anos", "12 e mais"))+
  theme_classic()+
  labs(x = "Escolaridade", y = "número de maes")+
  scale_fill_manual(values = c("#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3"))

p2<-ggplot(data = estado) + 
  geom_col(mapping = aes(x = estcivmae, y = n, fill = estcivmae), show.legend = F)+
  scale_y_continuous(labels = scales::comma)+
  scale_x_discrete(limits = c("1","2", "3", "4", "5"),
                   labels = c("Solteira", "Casada", "Viuva", "Divorciada", "União Consensual"))+
  theme_classic()+
  labs(x = "Estado civil", y = "número de maes")+
  scale_fill_manual(values = c("#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3"))

p3<-ggplot(data = raca) + 
  geom_col(mapping = aes(x = racacor, y = n, fill = racacor), show.legend = F)+
  scale_y_continuous(labels = scales::comma)+
  scale_x_discrete(limits = c("1","2", "3", "4", "5"),
                   labels = c("Branca", "Preta", "Amarela", "Parda", "Indigena"))+
  theme_classic()+
  labs(x = "Raça da mae", y = "número de maes")+
  scale_fill_manual(values = c("#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3"))

(p1 |p2)/ p3
  
```



## Variaveis numericas 

```{r, fig.align='center'}
birth %>% 
  gather(mesprenat:qtdpartces, key = "Diagnostico", value = "value") %>% 
  mutate(Diagnostico = as.factor(Diagnostico))-> resp

ggplot(resp, aes(x = reorder(Diagnostico, value), y = value, fill = Diagnostico)) +
  geom_boxplot(show.legend = FALSE)+
  theme_classic()+
  theme(axis.title.x = element_blank())+
  labs(y = "valores")

```


## Correlação de Spearman 

```{r, fig.align='center'}

birth[cols.fact] <- sapply(birth[cols.fact], as.numeric)
numeric_variables <- birth[ , purrr::map_lgl(birth, is.numeric)]
numeric_variables <- numeric_variables[,-1]

corr <- abs(cor(numeric_variables, method = "spearman"))

colors <- dmat.color(corr)
order <- order.single(corr)

birth %>% 
  mutate(classe = as.character(classe)) %>% 
  mutate(classe = as.factor(classe)) -> birth
  

corrplot(cor(numeric_variables),
         method = "circle",       
         order = "hclust",         
         hclust.method = "ward.D",
         addrect = 2,
         rect.col = 2,            
         rect.lwd = 2,
         addCoef.col = "white")  
```

